(defun cm_to_m (cm)
  (/ cm 100))

(defun double_m (m)
  (* m m))

(defun bmi (kg cm)
  (let ((result (/ kg (double_m (cm_to_m cm)))))
    (cond ((< result 18.5)
           (format t "BMI:~F 低体重（痩せ型）~%" result))
          ((< result 25)
           (format t "BMI:~F 普通体重~%" result))
          ((< result 30)
           (format t "BMI:~F 肥満（１度）~%" result))
          ((< result 35)
           (format t "BMI:~F 肥満（２度）~%" result))
          ((< result 40)
           (format t "BMI:~F 肥満（３度）~%" result))
          ((>= result 40)
           (format t "BMI:~F 肥満（４度）~%" result)))))
